AWSTemplateFormatVersion: '2010-09-09'
Description: S3 and CloudFront resources for static website hosting

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment
  ProjectName:
    Type: String
    Description: "Logical name/prefix for resources"

Resources:
  # S3 Bucket for static assets
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Public
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-website-bucket
        - Key: Environment
          Value: !Ref Environment

  # # CloudFront Distribution
  # CloudFrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #         - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
  #           Id: S3Origin
  #           S3OriginConfig:
  #             OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
  #       Enabled: true
  #       DefaultRootObject: index.html
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #           - GET
  #           - HEAD
  #           - OPTIONS
  #         TargetOriginId: S3Origin
  #         ForwardedValues:
  #           QueryString: false
  #           Cookies:
  #             Forward: none
  #         ViewerProtocolPolicy: redirect-to-https
  #       PriceClass: PriceClass_100
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: true
  #       Tags:
  #         - Key: Environment
  #           Value: !Ref Environment

  # CloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Sub ${AWS::StackName} OAI

  # Bucket Policy for CloudFront access
  # WebsiteBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref WebsiteBucket
  #     PolicyDocument:
  #       Statement:
  #         - Action:
  #             - s3:GetObject
  #           Effect: Allow
  #           Resource: !Sub ${WebsiteBucket.Arn}/*
  #           Principal:
  #             CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${WebsiteBucket.Arn}/*

Outputs:
  WebsiteBucketName:
    Description: S3 Bucket for website content
    Value: !Ref WebsiteBucket

  CloudFrontDistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName