AWSTemplateFormatVersion: '2010-09-09'
Description: vega website deploy

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: The deployment environment

  TemplateBucket:
    Type: String
    Description: S3 bucket containing CloudFormation templates

  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-03de7ad5a4c7c1822
    Description: ID of the existing company VPC
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-02615277a84a5fcb4,subnet-005d1ad197eb59c2b
    Description: List of existing subnet IDs for deployment
    
  DocumentsBucketName:
    Type: String
    Default: aiad-docs
    Description: Base name for the S3 bucket that will store documents

Resources:
  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/templates/security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Add more nested stacks as needed

  # Static Website Stack
  StaticWebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/templates/static-website.yaml
      Parameters:
        ProjectName: !Ref AWS::StackName
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment

# Outputs:
  # Your outputs will go here
Outputs:
  WebsiteBucketName:
    Description: S3 Bucket for website content
    Value: !GetAtt StaticWebsiteStack.Outputs.WebsiteBucketName
